In [2]:
#from xgboost import XGBClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score
import pandas as pd
from sklearn import preprocessing

#from xgboost import plot_importance
import numpy as np
from sklearn.metrics import confusion_matrix


from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [3]:
models = []
acc = []
precision = []
recall = []
f1 = []

In [4]:
df = pd.read_csv("train_LZdllcl.csv")
df.set_index('employee_id',inplace=True)

In [5]:
df

,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
employee_id,,,,,,,,,,,,,
65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0
58896,Analytics,region_2,Bachelor's,m,sourcing,2,31,3.0,7,0,0,85,0
20379,Operations,region_20,Bachelor's,f,other,1,31,3.0,5,0,0,59,0
16290,Operations,region_34,Master's & above,m,sourcing,1,33,3.0,6,0,0,63,0
73202,Analytics,region_20,Bachelor's,m,other,1,28,4.0,5,0,0,83,0
28911,Sales & Marketing,region_1,Master's & above,m,sourcing,1,32,5.0,5,1,0,54,0
29934,Technology,region_23,NaN,m,sourcing,1,30,NaN,1,0,0,77,0
49017,Sales & Marketing,region_7,Bachelor's,f,sourcing,1,35,5.0,3,1,0,50,1
60051,Sales & Marketing,region_4,Bachelor's,m,sourcing,1,49,5.0,5,1,0,49,0
38401,Technology,region_29,Master's & above,m,other,2,39,3.0,16,0,0,80,0
77040,R&D,region_2,Master's & above,m,sourcing,1,37,3.0,7,0,0,84,0
43931,Operations,region_7,Bachelor's,m,other,1,37,1.0,10,0,0,60,0
7152,Technology,region_2,Bachelor's,m,other,1,38,3.0,5,1,0,77,0
9403,Sales & Marketing,region_31,Bachelor's,m,other,1,34,1.0,4,0,0,51,0
17436,Sales & Marketing,region_31,Bachelor's,m,other,1,34,5.0,8,1,0,46,0
54461,Operations,region_15,Bachelor's,m,other,1,37,3.0,9,0,0,59,0
12067,Procurement,region_14,Bachelor's,m,other,1,35,3.0,7,0,0,75,0
33332,Operations,region_15,NaN,m,sourcing,1,41,4.0,11,0,0,57,0
58789,Finance,region_11,Bachelor's,f,other,1,28,3.0,4,0,0,63,0
71177,Procurement,region_5,Bachelor's,m,other,1,27,NaN,1,0,0,70,0
52057,Finance,region_22,Master's & above,m,sourcing,2,39,5.0,7,0,0,59,0
26585,Technology,region_22,Bachelor's,m,other,1,27,5.0,3,1,0,83,0
37749,Procurement,region_26,Bachelor's,m,other,1,31,5.0,4,1,0,68,0
2370,Technology,region_26,Bachelor's,m,other,1,33,4.0,4,0,0,79,0
8219,Analytics,region_5,Bachelor's,m,other,1,29,5.0,3,1,0,80,0
74759,Sales & Marketing,region_4,Bachelor's,m,sourcing,1,26,NaN,1,0,0,44,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30691,Procurement,region_2,Bachelor's,f,sourcing,1,30,3.0,3,0,0,70,0
49923,Technology,region_30,Bachelor's,f,sourcing,1,34,3.0,3,0,0,86,0
73767,Operations,region_19,Bachelor's,f,sourcing,1,39,5.0,7,0,0,60,0
76497,HR,region_27,Bachelor's,f,sourcing,1,38,5.0,3,1,0,50,0
17281,Operations,region_2,Below Secondary,m,sourcing,2,26,3.0,2,0,0,60,0
45504,Procurement,region_2,Below Secondary,m,other,3,23,3.0,2,0,0,71,0
68370,Sales & Marketing,region_30,Bachelor's,m,other,1,39,5.0,9,0,0,48,0
42055,Technology,region_26,Bachelor's,m,other,1,33,4.0,7,1,0,77,0
32291,Sales & Marketing,region_31,Bachelor's,f,sourcing,2,31,1.0,4,0,0,51,0
77455,Technology,region_27,Bachelor's,m,sourcing,4,26,3.0,3,0,0,84,0
75164,Sales & Marketing,region_13,Bachelor's,f,sourcing,2,28,3.0,3,0,0,48,0
75942,Sales & Marketing,region_7,Master's & above,m,other,3,31,3.0,9,0,0,50,0
67988,HR,region_2,Bachelor's,f,sourcing,1,48,5.0,4,0,0,49,0
27274,Technology,region_11,Bachelor's,m,sourcing,1,32,1.0,3,1,0,82,0
994,Sales & Marketing,region_14,Bachelor's,m,other,1,59,3.0,11,0,0,65,1
28400,Technology,region_2,Bachelor's,m,other,1,33,1.0,9,0,0,79,0
35000,Operations,region_16,Bachelor's,m,other,1,37,4.0,7,1,0,54,0
13477,Procurement,region_15,Master's & above,m,other,1,35,3.0,7,0,0,70,0
12592,Sales & Marketing,region_25,Master's & above,m,other,1,34,3.0,7,0,0,60,1
62450,Sales & Marketing,region_11,Bachelor's,m,sourcing,1,28,5.0,3,1,1,47,0
40257,Sales & Marketing,region_2,Master's & above,f,other,2,40,5.0,4,1,0,51,0
68093,Procurement,region_2,Master's & above,f,other,1,50,5.0,6,1,1,67,0
39227,HR,region_11,Bachelor's,m,other,2,34,5.0,3,0,0,52,0
12431,Technology,region_26,Bachelor's,f,sourcing,1,31,NaN,1,0,0,78,0
6915,Sales & Marketing,region_14,Bachelor's,m,other,2,31,1.0,2,0,0,49,0
3030,Technology,region_14,Bachelor's,m,sourcing,1,48,3.0,17,0,0,78,0
74592,Operations,region_27,Master's & above,f,other,1,37,2.0,6,0,0,56,0
13918,Analytics,region_1,Bachelor's,m,other,1,27,5.0,3,1,0,79,0
13614,Sales & Marketing,region_9,NaN,m,sourcing,1,29,1.0,2,0,0,45,0
51526,HR,region_22,Bachelor's,m,other,1,27,1.0,5,0,0,49,0

In [6]:
dfvalidation = pd.read_csv("test_2umaH9m.csv")
dfvalidation.set_index('employee_id',inplace=True)
#dfvalidation['is_promoted'] = 5

In [7]:
dfvalidation

,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score
employee_id,,,,,,,,,,,,
8724,Technology,region_26,Bachelor's,m,sourcing,1,24,NaN,1,1,0,77
74430,HR,region_4,Bachelor's,f,other,1,31,3.0,5,0,0,51
72255,Sales & Marketing,region_13,Bachelor's,m,other,1,31,1.0,4,0,0,47
38562,Procurement,region_2,Bachelor's,f,other,3,31,2.0,9,0,0,65
64486,Finance,region_29,Bachelor's,m,sourcing,1,30,4.0,7,0,0,61
46232,Procurement,region_7,Bachelor's,m,sourcing,1,36,3.0,2,0,0,68
54542,Finance,region_2,Bachelor's,m,other,1,33,5.0,3,1,0,57
67269,Analytics,region_22,Bachelor's,m,sourcing,2,36,3.0,3,0,0,85
66174,Technology,region_7,Master's & above,m,other,1,51,4.0,11,0,0,75
76303,Technology,region_22,Bachelor's,m,sourcing,1,29,5.0,2,1,0,76
60245,Sales & Marketing,region_16,Bachelor's,m,sourcing,2,40,5.0,12,1,0,50
42639,Sales & Marketing,region_17,Master's & above,m,sourcing,1,40,3.0,10,0,0,46
30963,Sales & Marketing,region_4,Master's & above,f,other,1,34,3.0,4,0,0,52
54055,Analytics,region_24,Bachelor's,m,other,1,37,3.0,10,0,0,82
42996,Operations,region_11,Bachelor's,m,sourcing,1,30,5.0,6,1,0,58
12737,Sales & Marketing,region_7,Bachelor's,m,sourcing,1,31,4.0,4,1,0,47
27561,Operations,region_27,Bachelor's,f,sourcing,1,26,5.0,3,0,0,56
26622,Sales & Marketing,region_17,Bachelor's,m,sourcing,1,40,5.0,6,1,0,50
31582,Procurement,region_7,Bachelor's,f,other,1,49,3.0,7,1,0,64
29793,Procurement,region_27,Bachelor's,m,other,1,27,2.0,5,0,0,65
72735,Sales & Marketing,region_9,Master's & above,m,sourcing,1,37,5.0,3,0,0,47
5677,Technology,region_17,Bachelor's,m,sourcing,1,25,NaN,1,0,0,80
60889,Technology,region_29,Master's & above,m,sourcing,1,30,1.0,3,0,0,83
51498,Procurement,region_4,Master's & above,m,other,1,41,3.0,4,0,0,76
8566,Finance,region_20,Bachelor's,f,other,1,29,4.0,6,1,0,58
53151,Operations,region_20,Bachelor's,m,other,1,33,3.0,7,1,1,62
16203,Sales & Marketing,region_17,Master's & above,m,sourcing,1,34,4.0,6,1,0,50
61083,Analytics,region_13,Bachelor's,m,sourcing,1,34,3.0,3,1,0,87
74849,Operations,region_22,Bachelor's,m,other,1,52,1.0,10,0,0,61
13259,Sales & Marketing,region_34,Bachelor's,m,sourcing,1,30,2.0,3,0,0,50
...,...,...,...,...,...,...,...,...,...,...,...,...
72190,Operations,region_32,Bachelor's,f,other,1,31,4.0,7,1,0,65
27155,Sales & Marketing,region_22,Bachelor's,f,other,2,27,4.0,4,0,0,48
15959,Analytics,region_31,Bachelor's,m,other,1,36,5.0,7,1,0,86
72900,Analytics,region_21,Bachelor's,m,other,1,30,3.0,3,1,0,87
57683,Analytics,region_2,Bachelor's,m,sourcing,2,25,1.0,2,1,0,83
55174,Technology,region_7,Bachelor's,f,sourcing,1,24,4.0,2,0,0,85
51115,Technology,region_2,Master's & above,f,other,1,40,4.0,10,0,0,76
50134,Technology,region_2,Bachelor's,m,referred,2,28,4.0,6,1,0,79
59775,Sales & Marketing,region_2,Bachelor's,m,other,1,32,2.0,6,1,0,49
14408,Procurement,region_26,Bachelor's,f,other,1,30,1.0,1,0,0,69
4351,Sales & Marketing,region_30,Bachelor's,m,sourcing,1,36,5.0,3,0,0,49
59625,Procurement,region_13,Master's & above,m,sourcing,1,40,4.0,9,1,0,69
29379,Technology,region_6,Bachelor's,f,other,1,29,3.0,3,0,0,87
67979,Operations,region_25,Master's & above,m,sourcing,1,38,3.0,8,0,0,57
61451,Operations,region_7,Master's & above,f,other,2,43,3.0,3,0,0,61
73871,Legal,region_27,Bachelor's,f,sourcing,1,28,3.0,2,0,0,61
52090,Sales & Marketing,region_2,Master's & above,f,other,1,51,4.0,8,0,0,50
18488,Procurement,region_2,Bachelor's,m,sourcing,3,28,4.0,6,0,0,68
59673,Procurement,region_17,Bachelor's,f,sourcing,1,27,4.0,3,1,0,69
39410,Sales & Marketing,region_2,Bachelor's,m,other,3,20,NaN,1,0,0,49
11837,Operations,region_33,Bachelor's,f,sourcing,1,29,5.0,6,1,0,60
78278,Operations,region_22,Master's & above,m,other,2,40,5.0,3,1,0,60
27284,Sales & Marketing,region_2,NaN,m,sourcing,2,44,4.0,4,0,0,49
49291,Sales & Marketing,region_30,Bachelor's,m,other,1,34,3.0,5,0,0,49
47537,Sales & Marketing,region_20,Bachelor's,m,other,1,28,4.0,2,0,0,51
53478,Legal,region_2,Below Secondary,m,sourcing,1,24,3.0,1,0,0,61
25600,Technology,region_25,Bachelor's,m,sourcing,1,31,3.0,7,0,0,74
45409,HR,region_16,Bachelor's,f,sourcing,1,26,4.0,4,0,0,50
1186,Procurement,region_31,Bachelor's,m,sourcing,3,27,NaN,1,0,0,70
5973,Technology,region_17,Master's & above,m,other,3,40,5.0,5,1,0,89

In [8]:
df.isnull().sum()

department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [9]:
df['education'].describe()

count          52399
unique             3
top       Bachelor's
freq           36669
Name: education, dtype: object

In [10]:
df['education'].fillna('Bachelor\'s', inplace=True)

In [11]:
df.isnull().sum()

department                 0
region                     0
education                  0
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [12]:
df.groupby(['previous_year_rating'])['previous_year_rating'].count().sort_values(ascending=False)

previous_year_rating
3.0    18618
5.0    11741
4.0     9877
1.0     6223
2.0     4225
Name: previous_year_rating, dtype: int64

In [13]:
df['previous_year_rating'].fillna(3.0, inplace=True)

In [14]:
df.isnull().sum()

department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [15]:
df.head()

,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
employee_id,,,,,,,,,,,,,
65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0

In [16]:
dfvalidation.isnull().sum()

department                 0
region                     0
education               1034
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    1812
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
dtype: int64

In [17]:
dfvalidation.groupby(['previous_year_rating'])['previous_year_rating'].count().sort_values(ascending=False)

previous_year_rating
3.0    7921
5.0    5097
4.0    4249
1.0    2680
2.0    1731
Name: previous_year_rating, dtype: int64

In [18]:
dfvalidation['education'].describe()

count          22456
unique             3
top       Bachelor's
freq           15578
Name: education, dtype: object

In [19]:
dfvalidation['previous_year_rating'].fillna(3.0, inplace=True)
dfvalidation['education'].fillna('Bachelor\'s', inplace=True)

In [20]:
dept = df['department'].unique()
dept

array(['Sales & Marketing', 'Operations', 'Technology', 'Analytics',
       'R&D', 'Procurement', 'Finance', 'HR', 'Legal'], dtype=object)

In [21]:
dept= list(df.groupby(['department'])['age'].mean().sort_values().index)
dept

['Finance',
 'Analytics',
 'R&D',
 'Legal',
 'HR',
 'Sales & Marketing',
 'Technology',
 'Procurement',
 'Operations']

In [22]:
ord_dict = {}
i=0
for d in dept:
    ord_dict[d] = i
    i = i+1
ord_dict

{'Finance': 0,
 'Analytics': 1,
 'R&D': 2,
 'Legal': 3,
 'HR': 4,
 'Sales & Marketing': 5,
 'Technology': 6,
 'Procurement': 7,
 'Operations': 8}

In [23]:
df['department_ord'] = df['department'].map(ord_dict)
dfvalidation['department_ord'] = dfvalidation['department'].map(ord_dict)

In [24]:
rc= list(df.groupby(['recruitment_channel'])['age'].mean().sort_values().index)
ord_dict = {}
i=0
for d in rc:
    ord_dict[d] = i
    i = i+1
ord_dict

{'referred': 0, 'sourcing': 1, 'other': 2}

In [25]:
df['recruitment_channel_ord'] = df['recruitment_channel'].map(ord_dict)
dfvalidation['recruitment_channel_ord'] = dfvalidation['recruitment_channel'].map(ord_dict)

In [26]:
rc= list(df.groupby(['region'])['age'].mean().sort_values().index)
ord_dict = {}
i=0
for d in rc:
    ord_dict[d] = i
    i = i+1
ord_dict

{'region_9': 0,
 'region_6': 1,
 'region_12': 2,
 'region_34': 3,
 'region_18': 4,
 'region_32': 5,
 'region_24': 6,
 'region_29': 7,
 'region_1': 8,
 'region_8': 9,
 'region_25': 10,
 'region_30': 11,
 'region_22': 12,
 'region_20': 13,
 'region_28': 14,
 'region_5': 15,
 'region_27': 16,
 'region_31': 17,
 'region_11': 18,
 'region_21': 19,
 'region_26': 20,
 'region_3': 21,
 'region_10': 22,
 'region_16': 23,
 'region_14': 24,
 'region_23': 25,
 'region_15': 26,
 'region_17': 27,
 'region_7': 28,
 'region_13': 29,
 'region_33': 30,
 'region_19': 31,
 'region_4': 32,
 'region_2': 33}

In [27]:
df['region_ord'] = df['region'].map(ord_dict)
dfvalidation['region_ord'] = dfvalidation['region'].map(ord_dict)

In [28]:
rc= list(df.groupby(['education'])['age'].mean().sort_values().index)
ord_dict = {}
i=0
for d in rc:
    ord_dict[d] = i
    i = i+1
ord_dict

{'Below Secondary': 0, "Bachelor's": 1, "Master's & above": 2}

In [29]:
df['education_ord'] = df['education'].map(ord_dict)
dfvalidation['education_ord'] = dfvalidation['education'].map(ord_dict)

In [30]:
df=pd.get_dummies(df, drop_first=True, columns=['gender'])
dfvalidation=pd.get_dummies(dfvalidation, drop_first=True, columns=['gender'])

In [31]:
df.head()

,department,region,education,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted,department_ord,recruitment_channel_ord,region_ord,education_ord,gender_m
employee_id,,,,,,,,,,,,,,,,,
65438,Sales & Marketing,region_7,Master's & above,sourcing,1,35,5.0,8,1,0,49,0,5,1,28,2,0
65141,Operations,region_22,Bachelor's,other,1,30,5.0,4,0,0,60,0,8,2,12,1,1
7513,Sales & Marketing,region_19,Bachelor's,sourcing,1,34,3.0,7,0,0,50,0,5,1,31,1,1
2542,Sales & Marketing,region_23,Bachelor's,other,2,39,1.0,10,0,0,50,0,5,2,25,1,1
48945,Technology,region_26,Bachelor's,other,1,45,3.0,2,0,0,73,0,6,2,20,1,1

In [32]:
dfvalidation.head()

,department,region,education,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,department_ord,recruitment_channel_ord,region_ord,education_ord,gender_m
employee_id,,,,,,,,,,,,,,,,
8724,Technology,region_26,Bachelor's,sourcing,1,24,3.0,1,1,0,77,6,1,20,1,1
74430,HR,region_4,Bachelor's,other,1,31,3.0,5,0,0,51,4,2,32,1,0
72255,Sales & Marketing,region_13,Bachelor's,other,1,31,1.0,4,0,0,47,5,2,29,1,1
38562,Procurement,region_2,Bachelor's,other,3,31,2.0,9,0,0,65,7,2,33,1,0
64486,Finance,region_29,Bachelor's,sourcing,1,30,4.0,7,0,0,61,0,1,7,1,1

In [33]:
dfvalidation.head()

,department,region,education,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,department_ord,recruitment_channel_ord,region_ord,education_ord,gender_m
employee_id,,,,,,,,,,,,,,,,
8724,Technology,region_26,Bachelor's,sourcing,1,24,3.0,1,1,0,77,6,1,20,1,1
74430,HR,region_4,Bachelor's,other,1,31,3.0,5,0,0,51,4,2,32,1,0
72255,Sales & Marketing,region_13,Bachelor's,other,1,31,1.0,4,0,0,47,5,2,29,1,1
38562,Procurement,region_2,Bachelor's,other,3,31,2.0,9,0,0,65,7,2,33,1,0
64486,Finance,region_29,Bachelor's,sourcing,1,30,4.0,7,0,0,61,0,1,7,1,1

In [34]:
df.head()

,department,region,education,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted,department_ord,recruitment_channel_ord,region_ord,education_ord,gender_m
employee_id,,,,,,,,,,,,,,,,,
65438,Sales & Marketing,region_7,Master's & above,sourcing,1,35,5.0,8,1,0,49,0,5,1,28,2,0
65141,Operations,region_22,Bachelor's,other,1,30,5.0,4,0,0,60,0,8,2,12,1,1
7513,Sales & Marketing,region_19,Bachelor's,sourcing,1,34,3.0,7,0,0,50,0,5,1,31,1,1
2542,Sales & Marketing,region_23,Bachelor's,other,2,39,1.0,10,0,0,50,0,5,2,25,1,1
48945,Technology,region_26,Bachelor's,other,1,45,3.0,2,0,0,73,0,6,2,20,1,1

In [35]:
df.shape

(54808, 17)

In [36]:
dfvalidation.shape

(23490, 16)

In [37]:
X = df.drop(columns=['is_promoted','department','region','education','recruitment_channel']).values

In [38]:
X.shape

(54808, 12)

In [39]:
y=df['is_promoted'].values

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, 
                                                    random_state = 0)

# Random Forest Classifier

In [41]:
#classification
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier() #baseline model
rfc.fit(X_train, y_train)

C:\Users\MUJ\Anaconda3\envs\deeplearning\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [42]:
y_pred_rfc = rfc.predict(X_test)
y_pred_rfc

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [43]:
print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred_rfc))
print('Accuracy Score',accuracy_score(y_test, y_pred_rfc))
print('F1_Score',f1_score(y_test, y_pred_rfc))
print('Precision Score',precision_score(y_test, y_pred_rfc))
print('Recall Score',recall_score(y_test, y_pred_rfc))

models.append('Random Forest Classifier')
acc.append(accuracy_score(y_test, y_pred_rfc))
f1.append(f1_score(y_test, y_pred_rfc))
precision.append(precision_score(y_test, y_pred_rfc))
recall.append(recall_score(y_test, y_pred_rfc))

Confusion Matrix
[[9947   94]
 [ 648  273]]
Accuracy Score 0.9323116219667944
F1_Score 0.42391304347826086
Precision Score 0.7438692098092643
Recall Score 0.2964169381107492

# Logistic Regression

In [44]:
#classification
from sklearn.linear_model  import LogisticRegression
lr = LogisticRegression() #baseline model
lr.fit(X_train, y_train)

C:\Users\MUJ\Anaconda3\envs\deeplearning\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [45]:
y_pred_lr = lr.predict(X_test)
y_pred_lr

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [46]:
print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred_lr))
print('Accuracy Score',accuracy_score(y_test, y_pred_lr))
print('F1_Score',f1_score(y_test, y_pred_lr))
print('Precision Score',precision_score(y_test, y_pred_lr)) 
print('Recall Score',recall_score(y_test, y_pred_lr))

models.append('Logistic Regression')
acc.append(accuracy_score(y_test, y_pred_lr))
f1.append(f1_score(y_test, y_pred_lr))
precision.append(precision_score(y_test, y_pred_lr))
recall.append(recall_score(y_test, y_pred_lr))

Confusion Matrix
[[10002    39]
 [  840    81]]
Accuracy Score 0.9198139025725233
F1_Score 0.15561959654178673
Precision Score 0.675
Recall Score 0.08794788273615635

# DecisionTreeClassifie

In [47]:
from sklearn.tree  import DecisionTreeClassifier
dt = DecisionTreeClassifier() #baseline model
dt.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [48]:
y_pred_dt = dt.predict(X_test)
y_pred_dt

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [49]:
print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred_dt))
print('Accuracy Score',accuracy_score(y_test, y_pred_dt))
print('F1_Score',f1_score(y_test, y_pred_dt))
print('Precision Score',precision_score(y_test, y_pred_dt)) 
print('Recall Score',recall_score(y_test, y_pred_dt))

models.append('Decision Trees')
acc.append(accuracy_score(y_test, y_pred_dt))
f1.append(f1_score(y_test, y_pred_dt))
precision.append(precision_score(y_test, y_pred_dt))
recall.append(recall_score(y_test, y_pred_dt))

Confusion Matrix
[[9453  588]
 [ 499  422]]
Accuracy Score 0.9008392629082285
F1_Score 0.43707923355774214
Precision Score 0.4178217821782178
Recall Score 0.4581976112920738

# Ada Boost Classifier

In [50]:
# Fitting AdaBoost Classification to the Training set
from sklearn.ensemble import AdaBoostClassifier
adb = AdaBoostClassifier()
adb.fit(X_train, y_train)
models.append('AdaBoost')

In [51]:
y_pred_adb = adb.predict(X_test)
y_pred_adb

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [52]:
print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred_adb))
print('Accuracy Score',accuracy_score(y_test, y_pred_adb))
print('F1_Score',f1_score(y_test, y_pred_adb))
print('Precision Score',precision_score(y_test, y_pred_adb)) 
print('Recall Score',recall_score(y_test, y_pred_adb))

acc.append(accuracy_score(y_test, y_pred_adb))
f1.append(f1_score(y_test, y_pred_adb))
precision.append(precision_score(y_test, y_pred_adb))
recall.append(recall_score(y_test, y_pred_adb))

Confusion Matrix
[[9986   55]
 [ 765  156]]
Accuracy Score 0.9251961320926838
F1_Score 0.2756183745583039
Precision Score 0.7393364928909952
Recall Score 0.16938110749185667

# SVM

In [53]:
from sklearn.svm  import SVC
svc = SVC() #baseline model
svc.fit(X_train, y_train)

C:\Users\MUJ\Anaconda3\envs\deeplearning\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [54]:
y_pred_svc = svc.predict(X_test)
y_pred_svc

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [55]:
print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred_svc))
print('Accuracy Score',accuracy_score(y_test, y_pred_svc))
print('F1_Score',f1_score(y_test, y_pred_svc))
print('Precision Score',precision_score(y_test, y_pred_svc)) 
print('Recall Score',recall_score(y_test, y_pred_svc))

models.append('SVM')
acc.append(accuracy_score(y_test, y_pred_svc))
f1.append(f1_score(y_test, y_pred_svc))
precision.append(precision_score(y_test, y_pred_svc))
recall.append(recall_score(y_test, y_pred_svc))

Confusion Matrix
[[10029    12]
 [  766   155]]
Accuracy Score 0.9290275497172049
F1_Score 0.2849264705882353
Precision Score 0.9281437125748503
Recall Score 0.16829533116178066

In [56]:
# Fitting Voting Classifier Classification to the Training set
from sklearn.ensemble import VotingClassifier
vc = VotingClassifier(estimators=[('Logistic Regression',lr),
                                   ('Decision Tree',dt),
                                   ('Random Forest',rfc),
                                   ('AdaBoost',adb),
                                   ('SVC',svc)
                                 ], 
                       voting='hard')
                       #flatten_transform=True)
vc.fit(X_train, y_train)
models.append('Average Ensemble')

C:\Users\MUJ\Anaconda3\envs\deeplearning\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\MUJ\Anaconda3\envs\deeplearning\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

In [57]:
models

['Random Forest Classifier',
 'Logistic Regression',
 'Decision Trees',
 'AdaBoost',
 'SVM',
 'Average Ensemble']

In [58]:
print('Confusion Matrix')
print(confusion_matrix(y_test,vc.predict(X_test)))
print('Accuracy Score',accuracy_score(y_test, vc.predict(X_test)))
print('F1_Score',f1_score(y_test,vc.predict(X_test)))
print('Precision Score',precision_score(y_test, vc.predict(X_test))) 
print('Recall Score',recall_score(y_test, vc.predict(X_test)))

acc.append(accuracy_score(y_test, vc.predict(X_test)))
f1.append(f1_score(y_test,vc.predict(X_test)))
precision.append(precision_score(y_test,vc.predict(X_test)))
recall.append(recall_score(y_test, vc.predict(X_test)))

Confusion Matrix
[[10026    15]
 [  745   176]]
Accuracy Score 0.9306695858419997
F1_Score 0.31654676258992803
Precision Score 0.9214659685863874
Recall Score 0.19109663409337677

In [59]:
model_dict = {'Models': models,
             'Accuracies': acc,
             'Precision': precision,
             'Recall': recall,
             'f1-score': f1}

In [60]:
model_df = pd.DataFrame(model_dict)
model_df

                     Models  Accuracies  Precision    Recall  f1-score
0  Random Forest Classifier    0.932312   0.743869  0.296417  0.423913
1       Logistic Regression    0.919814   0.675000  0.087948  0.155620
2            Decision Trees    0.900839   0.417822  0.458198  0.437079
3                  AdaBoost    0.925196   0.739336  0.169381  0.275618
4                       SVM    0.929028   0.928144  0.168295  0.284926
5          Average Ensemble    0.930670   0.921466  0.191097  0.316547

In [61]:
print(len(f1), len(recall),len(precision),len(acc),len(models))

6 6 6 6 6

In [62]:
models

['Random Forest Classifier',
 'Logistic Regression',
 'Decision Trees',
 'AdaBoost',
 'SVM',
 'Average Ensemble']

In [63]:
model_df = model_df.sort_values(['f1-score','Accuracies', 'Recall', 'Precision'],
                               ascending=False)

In [64]:
best_model = model_df['Models'].values[0]
best_model

'Decision Trees'

In [65]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = rfc, 
                             X = X_train, 
                             y = y_train, 
                             cv = 10)

In [66]:
from sklearn.metrics import make_scorer, f1_score, roc_auc_score

In [67]:
# Define scorer
def f1_metric(y_test, y_pred):
    score = f1_score(y_test, y_pred)
    return score

In [68]:
f1_scorer = make_scorer(f1_metric,greater_is_better=True)

In [ ]:
# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV
parameters = {"n_estimators" : [150,200,300,450,500],
              "criterion":['gini','entropy'],
              "max_depth": [3,5,7,10],
              "min_samples_split": [50, 30],
              "min_samples_leaf": [1, 5, 15],
              "min_weight_fraction_leaf": [0.1, 0.0025, 0.005],
              #"splitter": ['best','random']
              }

grid_search = GridSearchCV(estimator = rfc,
                           param_grid = parameters,
                           scoring = f1_scorer,
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)

In [ ]:
best_parameters = grid_search.best_params_
best_parameters

In [144]:
best_accuracy = grid_search.best_score_
best_accuracy

0.37689725576378036

In [145]:
# Fitting Final Model on training set
from sklearn.tree import DecisionTreeClassifier

tunedDTC=DecisionTreeClassifier (n_estimators = best_parameters["n_estimators"]
                                 criterion = best_parameters["criterion"],
                                 splitter = best_parameters["splitter"],
                                 max_depth = best_parameters["max_depth"],
                                 min_samples_split = best_parameters["min_samples_split"],
                                 min_samples_leaf = best_parameters["min_samples_leaf"],
                                 min_weight_fraction_leaf=best_parameters["min_weight_fraction_leaf"]
                                 )
tunedDTC.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=10,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=50,
                       min_weight_fraction_leaf=0.0025, presort=False,
                       random_state=None, splitter='best')

In [146]:
print('Confusion Matrix for Tuned RF: \n',confusion_matrix(y_test, tunedDTC.predict(X_test)))
print('Accuracy for Tuned RF: \n',accuracy_score(y_test, tunedDTC.predict(X_test)))
acc.append(accuracy_score(y_test, tunedDTC.predict(X_test)))
print('Precision for Tuned RF: \n',precision_score(y_test, tunedDTC.predict(X_test)))
precision.append(precision_score(y_test, tunedDTC.predict(X_test)))
print('Recall for Tuned RF: \n',recall_score(y_test, tunedDTC.predict(X_test)))
recall.append(recall_score(y_test, tunedDTC.predict(X_test)))
print('f1_score for Tuned RF: \n',f1_score(y_test, tunedDTC.predict(X_test)))
f1.append(f1_score(y_test, tunedDTC.predict(X_test)))

Confusion Matrix for Tuned RF:
 [[9970   71]
 [ 680  241]]
Accuracy for Tuned RF:
 0.931490603904397
Precision for Tuned RF:
 0.7724358974358975
Recall for Tuned RF:
 0.26167209554831705
f1_score for Tuned RF:
 0.3909164639091647

In [147]:
dfvalidation.head()

,department,region,education,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,department_ord,recruitment_channel_ord,region_ord,education_ord,gender_m
employee_id,,,,,,,,,,,,,,,,
8724,Technology,region_26,Bachelor's,sourcing,1,24,3.0,1,1,0,77,6,1,20,1,1
74430,HR,region_4,Bachelor's,other,1,31,3.0,5,0,0,51,4,2,32,1,0
72255,Sales & Marketing,region_13,Bachelor's,other,1,31,1.0,4,0,0,47,5,2,29,1,1
38562,Procurement,region_2,Bachelor's,other,3,31,2.0,9,0,0,65,7,2,33,1,0
64486,Finance,region_29,Bachelor's,sourcing,1,30,4.0,7,0,0,61,0,1,7,1,1

In [149]:
X = dfvalidation.drop(columns=['department','region','education','recruitment_channel']).values
#p=pd.read_csv('test_2umaH9m.csv')
pred = tunedDTC.predict(X)
submission_df = dfvalidation.copy()
#submission_df['employee_id']=p['employee_id']
#submission_df.set_index('employee_id',inplace=True)
#submission_df=submission_df.drop(columns=['department','region','education','recruitment_channel']).values
submission_df['is_promoted'] = pred
submission_df['employee_id']=submission_df.index
submission_df = submission_df[['employee_id','is_promoted']]
submission_df.to_csv('submission_ml.csv', index=False)